dataset:
  root_dir: ../data
  name: MonthPriceSalesDataset
  parameters:
    split_info:
      validation: 32
      test: 33
  # TODO: Move pipeline to a group of configs.
  pipeline:
    name: MonthPriceSalesPipeline
    parameters:
      drop_columns:
        - item_name
        - item_category_name
        - shop_name
        - city_name
        - date
        - item_revenue
        - category_company_average_item_sales
        - category_city_average_item_sales
        - category_shop_average_item_sales
      # TODO: Check again if all the categorical features are added.
      categorical_features:
#        - item_id
#        - item_category_id
#        - shop_id
#        - city_id
        - country_part
        - month
        - is_new_item
        - is_first_shop_transaction
      features:
        - name: time
        - name: revenue
        - name: city
        - name: is_new_item
        - name: is_first_shop_transaction
        - name: category_sales
          parameters:
            levels:
              - company
              - city
              - shop
        - name: lags
          parameters:
            item_sales:
              lags: [1, 2, 3]
              fill_value: 0
            category_company_average_item_sales:
              lags: [ 1, 2, 3 ]
              fill_value: 0
            category_company_average_item_price:
              lags: [ 1, 2 ]
              fill_value: 0
            category_city_average_item_sales:
              lags: [ 1, 2, 3 ]
              fill_value: 0
            category_city_average_item_price:
              lags: [ 1 ]
              fill_value: 0
            category_shop_average_item_sales:
              lags: [ 1, 2, 3 ]
              fill_value: 0
            category_shop_average_item_price:
              lags: [ 1, 2 ]
              fill_value: 0
            item_revenue:
              lags: [ 1 ]
              fill_value: 0
runner:
  models:
    - name: persistence
      parameters:
        hyper_parameters:
          predict_column: item_sales_lag_1
    - name: linear_regression
      parameters: {}
    - name: lightgbm
      parameters:
        hyper_parameters:
          objective: mse
          metric: rmse
          num_boost_round: 3000
          num_leaves: 127
          learning_rate: 0.005
          feature_fraction: 0.75
          bagging_fraction: 0.75
          bagging_freq: 5
          seed: 1
        meta_parameters:
          early_stopping_rounds: 6
          evaluation_period: 250
    - name: xgboost
      parameters:
        hyper_parameters:
          objective: reg:squarederror
          eval_metric: rmse
          num_boost_round: 3000
          nthread: 4
          n_estimators: 100
          reg_lambda: 1
          gamma: 0
          max_depth: 3
          eta: 1
        meta_parameters:
          early_stopping_rounds: 6
          evaluation_period: 250

