path:
  dataset: ../data
dataset:
  name: MonthPriceSalesDataset
  parameters: {}
  pipeline:
    name: MonthPriceSalesPipeline
    parameters:
      features:
        - name: time
        - name: revenue
        - name: city
        - name: is_new_item
        - name: is_first_shop_transaction
        - name: category_sales
          parameters:
            levels:
              - company
              - city
              - shop
        - name: lags
          parameters:
            item_sales:
              lags: [1, 2, 3]
              fill_value: 0
            category_company_average_item_sales:
              lags: [ 1, 2, 3 ]
              fill_value: 0
            category_company_average_item_price:
              lags: [ 1, 2 ]
              fill_value: 0
            category_city_average_item_sales:
              lags: [ 1, 2, 3 ]
              fill_value: 0
            category_city_average_item_price:
              lags: [ 1 ]
              fill_value: 0
            category_shop_average_item_sales:
              lags: [ 1, 2, 3 ]
              fill_value: 0
            category_shop_average_item_price:
              lags: [ 1, 2 ]
              fill_value: 0
            item_revenue:
              lags: [ 1 ]
              fill_value: 0
models:
  - name: persistence
    parameters:
      predict_column: item_sales_lag_1
  - name: linear_regression
    parameters: {}
  - name: lightgbm
    parameters: {}
  - name: xgboost
    parameters: {}
